# Generated by Django 4.0.6 on 2022-07-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(verbose_name='Temperature')),
                ('humidity', models.SmallIntegerField(verbose_name='Humidité')),
                ('pressure', models.FloatField(verbose_name='Pression')),
                ('wind_speed', models.FloatField(verbose_name='Vitesse actuel du vent')),
                ('average_wind_speed', models.FloatField(verbose_name='Vitesse moyenne du vent')),
                ('max_wind_speed_10min', models.FloatField(verbose_name='Vitesse actuel du vent')),
                ('wind_direction', models.CharField(max_length=5, verbose_name='Direction du vent')),
                ('battery', models.SmallIntegerField(verbose_name='battery')),
            ],
        ),
        migrations.CreateModel(
            name='InsideActualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(verbose_name='Temperature')),
                ('humidity', models.SmallIntegerField(verbose_name='Humidité')),
                ('pressure', models.FloatField(verbose_name='Pression')),
            ],
        ),
        migrations.CreateModel(
            name='LongTermData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(verbose_name='Temperature')),
                ('humidity', models.SmallIntegerField(verbose_name='Humidité')),
                ('pressure', models.FloatField(verbose_name='Pression')),
                ('wind_speed', models.FloatField(verbose_name='Vitesse actuel du vent')),
                ('average_wind_speed', models.FloatField(verbose_name='Vitesse moyenne du vent')),
                ('max_wind_speed_10min', models.FloatField(verbose_name='Vitesse actuel du vent')),
                ('wind_direction', models.CharField(max_length=5, verbose_name='Direction du vent')),
                ('battery', models.SmallIntegerField(verbose_name='battery')),
            ],
        ),
    ]
