# Generated by Django 4.1.4 on 2022-12-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Weather", "0004_alter_actualdata_max_wind_speed_10min"),
    ]

    operations = [
        migrations.AlterField(
            model_name="longtermdata",
            name="average_wind_speed",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Vitesse moyenne du vent"
            ),
        ),
        migrations.AlterField(
            model_name="longtermdata",
            name="battery",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="battery"
            ),
        ),
        migrations.AlterField(
            model_name="longtermdata",
            name="humidity",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Humidité"
            ),
        ),
        migrations.AlterField(
            model_name="longtermdata",
            name="max_wind_speed_10min",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Vitesse maximum du vent sur 10 min"
            ),
        ),
        migrations.AlterField(
            model_name="longtermdata",
            name="pressure",
            field=models.FloatField(blank=True, null=True, verbose_name="Pression"),
        ),
        migrations.AlterField(
            model_name="longtermdata",
            name="temperature",
            field=models.FloatField(blank=True, null=True, verbose_name="Temperature"),
        ),
        migrations.AlterField(
            model_name="longtermdata",
            name="wind_direction",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Direction du vent"
            ),
        ),
    ]
