# Generated by Django 4.1.4 on 2022-12-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Weather", "0005_alter_longtermdata_average_wind_speed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualdata",
            name="wind_direction",
            field=models.CharField(max_length=10, verbose_name="Direction du vent"),
        ),
        migrations.AlterField(
            model_name="longtermdata",
            name="wind_direction",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Direction du vent"
            ),
        ),
    ]
