# Generated by Django 4.1.4 on 2022-12-20 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Weather", "0006_alter_actualdata_wind_direction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualdata",
            name="time",
            field=models.DateTimeField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="insideactualdata",
            name="time",
            field=models.DateTimeField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="longtermdata",
            name="time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date"
            ),
        ),
    ]
